version: '3.9'

services:
  db:
    image: mongo:latest
    container_name: mongodbstage
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodbstage:27017/
  nodeapp:
    image: nodeapp
    container_name: nodeapp
    ports:
      - 5000:5000

  web-server:
    image: nginx:latest
    container_name: webserverstage
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx-default-stage.conf:/etc/nginx/conf.d/default.conf